### ISSUE TITLE
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.

### ISSUE THREAD

**Issue by tan-yuwei** [franciscozorrilla/metaGEM#106]
Dear Francisco,

Hi! :)

I tried to run a commond  {bash metaGEM.sh -t check}, it returned as below:
___________________________________________________________________________________________________
Setting current directory to root in config.yaml file ... 

Checking if conda is available ... detected version 4.12.0!
Searching for metaGEM conda environment ... detected! Activating metagem env ... 

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

Searching for metaWRAP conda environment ... detected!
Searching for prokka-roary conda environment ... detected!
__________________________________________________________________________________________
Could you tell me how can I properly configured shell? Many thanks in advance!

Best,
Yuwei

**Comment by franciscozorrilla** [comment]
Hi Yuwei,

I encourage you to set up & use metaGEM on your university's high performance computer cluster (HPC), instead of trying to install on your local machine. Your university's HPC will likely have conda installed as a loadable module, so you would not run into this problem when using metaGEM as described in the [methods section of the paper](https://academic.oup.com/nar/article/49/21/e126/6382386#319702632). 

This issue has more to do with setting up conda on your local machine rather than with metaGEM itself, so please refer to [google search](https://www.google.com/search?client=firefox-b-d&q=CommandNotFoundError%3A+Your+shell+has+not+been+properly+configured+to+use+'conda+activate'.+To+initialize+your+shell%2C+run) + the [conda documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html) to learn how to set up conda on your machine. It looks like the solution to your question is in the error message you posted:

> CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
> To initialize your shell, run
> 
> $ conda init <SHELL_NAME>
> 
> Currently supported shells are:
> 
>    * bash
>    * fish
>    * tcsh
>    * xonsh
>    * zsh
>    * powershell
> 
> See 'conda init --help' for more information and options.
> 
> IMPORTANT: You may need to close and restart your shell after running 'conda init'.

e.g. if you have a mac try `conda init zsh`
Happy to help with any questions more specifically related to metaGEM.

Best,
Francisco

**Comment by tan-yuwei** [comment]
Hi Francisco,

Many thanks for your reply. Your response helpled me a lot.

Best regards,
Yuwei

**Comment by franciscozorrilla** [comment]
No problem, good luck with your analysis!
