### ISSUE TITLE
[Question]: How to define and construct a custom culture medium component that can be recognized by CarveMe?

### ISSUE THREAD

**Issue by microbial-cookie** [franciscozorrilla/metaGEM#144]
hi developer,

Recently I have been using Carveme to construct a metabolic model for a single microbial genome. However, the nutrient component (Bis(2-ethylhexyl) phthalate, chemical formula: C24H38O4) I am using does not have a corresponding BIGG ID, so I cannot perform the necessary gap-filling in my own medium. Can you help me add it so that I can proceed with the analysis? The substance I am interested in is Bis(2-ethylhexyl) phthalate, chemical formula: C24H38O4. Look forward to your reply and hope to get your help. Thank you！

Ruiwen

**Comment by franciscozorrilla** [comment]
Hey @microbial-cookie,

This is a broader metabolic modelling question rather than a CarveMe/metaGEM specific query, but I will try my best to guide you in the right direction. Please read the online documention to understand how you can add metabolite and reactions to models, it is quite a straightforward process. This can be done using packages like [cobrapy](https://cobrapy.readthedocs.io/en/latest/building_model.html), [reframed](https://reframed.readthedocs.io/en/latest/basics.html), or [RAVEN](https://github.com/SysBioChalmers/RAVEN/wiki/Tutorials) (see also [this protocol ](https://link.springer.com/protocol/10.1007/978-1-0716-2399-2_16#Sec6)for example code).

Good luck!

**Comment by franciscozorrilla** [comment]
Just to clarify my previous answer, there is no point in adding metabolites that are not present in the BiGG database to the media composition for gapfilling, since these are not present in the universal model and so associated reactions will not be present in your CarveMe model output. That is why I suggest that you manually add the desired metabolites + associated reactions to your model. I recommend having a detailed look at the CarveMe [paper](https://academic.oup.com/nar/article/46/15/7542/5042022), so that you can understand the relationship between the universal model, the BiGG database, and your CarveMe output model.
