### ISSUE TITLE
troubleshooting: poor assembly/binning in complex samples

### ISSUE THREAD

**Issue by zoey-rw** [franciscozorrilla/metaGEM#62]
Hi Francisco! I think a poor assembly is preventing soil samples from producing decent bins. I do plan to try re-assembling with a lower minimum contig length, but I was wondering if you have any other advice for troubleshooting these samples.

In addition to the assembly stats from Megahit, I've included the final and intermediate binning results from the refined_bins directory. When running metaWRAP manually, the results are similarly dismal (had to lower the completeness to 15% to get output). This is one of three samples that ran through metaGEM, and I'm hoping that running ~40 additional samples will improve the MAGs.

Thank you,
Zoey
![intermediate_binning_results](https://user-images.githubusercontent.com/29359782/123979147-75cec280-d98e-11eb-8e0d-4f8c8ddc008f.png)
![binning_results](https://user-images.githubusercontent.com/29359782/123979159-78311c80-d98e-11eb-98bb-5016aa1868e7.png)
![assemblyVis](https://user-images.githubusercontent.com/29359782/123979214-841cde80-d98e-11eb-9bae-3c552676d355.png)

**Comment by franciscozorrilla** [comment]
Hi Zoey,

Thanks for using `metaGEM` and sharing your analysis!
Here are some of my thoughts based on your results:

1. I am not sure if lowering the minimum contig length for reassembly will help in your case, as the default is currently set to the low value of 1000 bp. Most binners cannot handle contigs any shorter than this, and many people like to *increase* rather than *decrease* the minimum contig length parameter for the assembler/binners, as this can result in less noisy binning since smaller contigs are harder to bin.

2. I agree that adding more samples should significantly improve the number and quality of recovered bins. I don't think I've ever seen such poor binning, not even a single medium quality bin! 😢 However, this is very heavily influenced by quality and size of the assemblies: the average contig sizes are very small! You may be able to improve the assemblies by playing around with other `MEGAHIT` parameters (run `megahit -h` to see options), e.g. you may have better luck with `--presets meta-large` instead of the default `meta-sensitive`.

3. I am generally not a fan of co-assembling samples, but if they are technical or biological replicates you may be able to get away with co-assembly and this would likely improve the quality of your bins (at the risk of generating chimeric bins).

4. Could you provide more information about the nature/source of your samples, e.g. is it bulk soil or plant-root-associated or lab culture of soil microbes, etc? I would also be interested in seeing the quality filtering results/visualization plot, did a lot of data get filtered out? I ask because your assemblies look very very small, perhaps the samples were not sequenced sufficiently deep enough to reconstruct genomes. Two of them are only ~5Mbp and split between ~3000 contigs, so no surprise that you don't get complete genomes from those. 

5. As a references, here are the quality filtering + assembly plots for the soil datasets we analyzed in the `metaGEM` [manuscript](https://www.biorxiv.org/content/10.1101/2020.12.31.424982v2.full). Note that the assembly plots were generated with an old script, and previously I was not using the minimum contig length of 1000 for megahit, so that is why there is the distinction in the legend.
    - Plant-associated: [quality filtering](https://github.com/franciscozorrilla/metaGEM/files/6754260/qfilterVis.pdf), [assembly](https://github.com/franciscozorrilla/metaGEM/files/6754231/assemblyVis.pdf), generated 172 MQ + HQ MAGs
    - Bulk-soil: [quality filtering](https://github.com/franciscozorrilla/metaGEM/files/6754259/qfilterVis.pdf), [assembly](https://github.com/franciscozorrilla/metaGEM/files/6754245/assemblyVis.pdf), generated 274 MQ +HQ MAGs

Hope some of this is useful and please let me know if you have further questions!

Best,
Francisco

**Comment by zoey-rw** [comment]
Thank you so much for the thorough response! Your comments do makes sense. Our assembly had already been running before I saw this advice, but if we have to re-run we will stick to 1000 or 1500. I've attached the assemblyVis plot for the larger dataset - the average contig length is under 750, so we'll see if that poses problems for binning...

[assemblyVis.pdf](https://github.com/franciscozorrilla/metaGEM/files/6787572/assemblyVis.1.pdf)

**Comment by franciscozorrilla** [comment]
No problem, feel free to share any future results as well! Based on your last assemblyVis plot I would expect you to be able to generate some MQ/HQ MAGs from the largest assemblies. 
Your results remind me of another [dataset](https://www.ncbi.nlm.nih.gov/bioproject/PRJEB18701/) I previously analyzed [without much success](https://github.com/franciscozorrilla/metaGEM/files/6868058/assemblyVis.pdf); I suspect that the sequencing depth may not be high enough to reconstruct large communities of MAGs for some soil datasets.

Best,
Francisco
