### ISSUE TITLE
other inputs

### ISSUE THREAD

**Issue by smb20200615** [franciscozorrilla/metaGEM#85]
Is there a way to input MAGs that we have generated using other pipelines into the tool? If so, at what point?

**Comment by smb20200615** [comment]
sorry for the subsequent question. When I run refinement it still tries to rerun the samples that failed. I have been following the steps of the tutorial.

**Comment by franciscozorrilla** [comment]
No problem, happy to help with your questions. 
OK that makes sense, since the `binRefine` rule takes in 3 inputs and you are missing one of them.
https://github.com/franciscozorrilla/metaGEM/blob/eb0860945fd0d8efa8495aeb441b55969c4e97b1/Snakefile#L879-L883
I would recommend trying to "trick" snakemake into thinking it already created the files by creating a dummy folder for those samples that failed to generate any bins with maxbin, e.g. `mkdir maxbin/sample/sample.maxbin-bins`. I believe that this is what I have done in the past, since `metaWRAP` will accept an empty folder and just proceed with the remaining draft bin sets. 

Please let me know if this works for you. If so, then I will try to modify the `maxbin` rule so that it creates this dummy directory if the binning fails to generate any MAGs.

**Comment by smb20200615** [comment]
Thank you so much! That fixed it. I was wondering if the metabolic models were done just for the prokaryotic MAGs. Also, do you have guidance on how to adapt the media config parameter for our biome of interest?

**Comment by franciscozorrilla** [comment]
Glad to hear it worked!

**Comment by franciscozorrilla** [comment]
Glad to hear it worked!

Indeed, CarveMe only reconstructs models for prokaryotic MAGs. Regarding media, this is something that you would have to adapt/design based on literature/domain knowledge and using metabolite IDs from the [bigg](http://bigg.ucsd.edu/) database. What biome are your samples from?
