### ISSUE TITLE
Regarding the result data counts in Zenodo for European women samples

### ISSUE THREAD

**Issue by jckim012** [franciscozorrilla/metaGEM#87]
Hi Francisco,

I downloaded the simulation result data as you guided in the issue #84. I am trying to analyze and reproduce the result data you provided in Zenodo for European 145 NGT/IGT/T2D women samples.

I have questions regarding the result data counts. If we look at the result data in GEMs and SMETANA folders, it has only 137 and 123 data, respectively, from total 145 European women samples. It looks like you selected data for the simulation.

Also, if we look at the 123 result data in SMETANA folder, 32 result data are vacant in the files. It looks like SMETANA did not generate results for these 32 omitted cases.

Could you give an explanation about these result data counts and data omission?

Sincerely,

Jin

**Comment by franciscozorrilla** [comment]
Hi Jin,

Indeed, the original publication generated a dataset of 145 samples, but only 137 were analyzed for the metaGEM paper. The missing 8 samples here were simply excluded because either the R1 or R2 file was corrupted or failed to download. 

The samples without any SMETANA file output failed to finish running prior to the cluster walltime job limit of 7 days, likely due to the large size of the community network. For example, it looks like there were 11 samples with over 50 GEMs generated, but only one of those successfully generated the SMETANA output. 

It is the opposite story for the samples with very few GEMs, e.g. under 10 per sample. Many of these fail to generate metabolic interaction predictions likely because they do not require any metabolite exchanges for maintaining a non-zero growth in the community given the simulation media.

I hope you will find these answers helpful, and please let me know if you have any further questions.

Best wishes,
Francisco

**Comment by jckim012** [comment]
Thank you very much! Your answers are very helpful to understand!
