### ISSUE TITLE
Question about CarveMe, SMETANA media

### ISSUE THREAD

**Issue by yhbae6022** [franciscozorrilla/metaGEM#91]
Dear Zorrilla,

In your paper, it is not clear which medium is used in the CarveMe simulation. And it is understood that M11 is used in SMETANA simulation.

However, in Snakefile and config.yaml file, it seems that CarveMe uses M8 and SMETANA uses all media (M1~M16).

Could you tell me what is causing these differences?

And what difference occurs in simulation when using one medium and multiple types of medium?

Regards,
Young-Ho

**Comment by franciscozorrilla** [comment]
Dear Young-Ho,

Thank you for your interest in our work! Your questions are answered in the methods section of the metaGEM [paper](https://academic.oup.com/nar/article/49/21/e126/6382386#319702632):

> ### Community simulations
> 
> The SMETANA v1.2.0 tool was used for simulating gut microbiome communities of reconstructed genome scale metabolic models. The ‘smetana’ command was used with the flags ‘–flavor fbc2 –detailed –mediadb media_db.tsv -m M11’ and using the default CPLEX solver v12.8. The simulation media was the same as was used for gapfilling (full media, M3) minus aromatic amino acids (M11). The media file was obtained from the authors of previous publication (16), and can be accessed from the metaGEM GitHub repository (https://github.com/franciscozorrilla/metaGEM).

You can see the composition of different media in figure 1D of the referenced [publication](https://www.nature.com/articles/s41564-018-0123-9):

![image](https://user-images.githubusercontent.com/35606471/145984230-6bb7e334-2b99-43b2-abe2-cb93c39134a3.png)

Note that in the media file M8 and M3 have the same exact composition since mucin is not present in the metabolic models generated by CarveMe, as it is not a metabolite in the BiGG database.

In summary, we gapfilled the metabolic models using M3 (equivalent to M8), and simulated the models in M11 media.

I also want to clarify that CarveMe does not do any "simulation" as you suggest, this software simply creates a genome scale metabolic model from a fasta file + gapfills on a particular media. SMETANA is the software that predict metabolic exchanges between models. Of course, the predicted exchanges will be a function of the metabolic models and the media composition used for gapfilling/simulation. 

For example, if you gapfill 2 community members on full/complete media and try to simulate metabolic exchanges in the same media then you will get no interactions. This is because CarveMe gapfilled the models so that they can grow purely on the media without needing any additional metabolites. On the other hand, if you gap-fill models on full/complete media and then try to simulate metabolic exhanges in a less-rich-media (e.g. remove certain metabolites from the gapfilling media), then SMETANA will predict the metabolic exchanges that are possible in order to sutain growth of all community members in the given simulation media.

I hope this helps clear things up, and please let me know if you have any further questions.

Best wishes,
Francisco

**Comment by yhbae6022** [comment]
Thank you very much.
Your answers are very helpful for me to understand your paper more.

I have another question.

You have used M11 for SMETANA.

In my opionion, the reason for using M11 for SMETANA is three strains, B. clarus, B. xylanisolvens and P. merdae
could not grow in the presense of aromatic amino acids.

Is that right?

Best regards,
Young-Ho

**Comment by yhbae6022** [comment]
Thank you very much, Mr. Zorrilla.
Your answers are very helpful for me to understand your paper more.

Best regards,
Young-Ho

**Comment by yhbae6022** [comment]
Thank you very much, Mr. Zorrilla.
Your answers are very helpful for me to understand your paper more.

Best regards,
Young-Ho
